#!/bin/bash -
command -v bsplit >/dev/null 2>&1 || { echo >&2 "I require bsplit but it's not installed. Aborting."; exit 1; }
function print_usage {
  echo "Usage: `basename $0` #number_of_splits_levels"
}
if [ $# -eq 0 ] ; then
  echo "The maximum number of splits level must be passed as argument"
  print_usage
  exit 1
fi
Nl=$1
rm -f bsplit*.log
for l in $(seq 1 $Nl); do
  echo "Running bsplit over level $l"
  lz=`printf "%4.4d" $l`
  ln -fs bsplit$lz.par bsplit.par
  bsplit >> bsplit$lz.log 2>&1
done
